version: "3"
services:
  directus:
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      - ./extensions:/directus/extensions
    environment:
      - ADMIN_EMAIL
      - ADMIN_PASSWORD
      - SECRET
      - KEY
      - CACHE_ENABLED
      - CACHE_TTL
      - CORS_CREDENTIALS
      - CORS_ENABLED
      - CORS_ORIGIN
      - DB_CLIENT
      - DB_DATABASE
      - DB_PORT
      - DB_SSL
      - DB_HOST
      - DB_USER
      - DB_PASSWORD
      - EXTENSIONS_PATHS
      - NPM_CONFIG_UPDATE_NOTIFIER
      - STORAGE_LOCATIONS
      - STORAGE_AMAZON_DRIVER
      - STORAGE_AMAZON_BUCKET
      - STORAGE_AMAZON_REGION
      - STORAGE_AMAZON_ENDPOINT
      - STORAGE_AMAZON_KEY
      - STORAGE_AMAZON_SECRET
